### ISSUE TITLE
Discriminator Loss

### ISSUE THREAD

**Issue by abi98213** [rosinality/progressive-gan-pytorch#2]
First of all thanks for your very intuitive implementation.
I was following your code but I saw
        

     

        fake_image = generator(
            Variable(torch.randn(b_size, code_size)).cuda(),
            label, step, alpha)
        fake_predict, fake_class_predict = discriminator(
            fake_image, step, alpha)
        fake_predict = fake_predict.mean()
        fake_predict.backward(one)
        real_predict, real_class_predict = discriminator(
        real_image, step, alpha)
        real_predict = real_predict.mean() \
         - 0.001 * (real_predict ** 2).mean()
        real_predict.backward(mone)
But I think so we should be passing one to real_predict and mone to fake_predict because discriminator must realize that fake_images must be given mone label and real_images must be given one label ?
Please explain me

**Comment by rosinality** [comment]
It is not a kind of label, but it will change the sign of gradient. So discriminator loss will be disc(fake) - disc(real) and generator loss is -disc(fake), so discriminator loss will make disc(fake) smaller & disc(real) larger, and generator loss will make disc(real) larger. So it will match with the formula in the paper:
min_G max_D E[D(real)] - E[D(fake)]
